### ISSUE TITLE
Intelligent cursor restoration after auto-formatting

### ISSUE THREAD

**Issue by danlamanna** [ubolonton/emacs-tree-sitter#28]
I've never used tree-sitter so let me know if this is not possible or doesn't make much sense.

Restoring buffer position after applying styling fixes can be difficult. My frequent use case is with the `black` formatter using https://github.com/lassik/emacs-format-all-the-code on save. 

Black makes a guarantee that the AST is unmodified after formatting, so it seems to me that combining tree-sitter with this the user could be placed on the same tree node as they were before the format. This would make it so that autoformatting would leave your cursor in the same logical place as it was before, even if the number of lines of code was radically changed.

**Comment by ubolonton** [comment]
This is a nice idea! I think it can be done as followed:
- Before formatting, store the "path" leading from the root node to the current node.
- After formatting, use that path to search for the corresponding node in the new syntax tree.

**Comment by maxbrunsfeld** [comment]
I think you could use [`TreeCursor::goto_first_child_for_byte`](https://github.com/tree-sitter/tree-sitter/blob/5670dd67056033750090b06942e619a23d280e6d/lib/binding_rust/lib.rs#L1103-L1116) to walk the cursor to the leaf node at a given byte offset (based on the cursor position) keeping track of the steps along the way.

**Comment by ubolonton** [comment]
There's a macro in 0.5.0 for this: `tree-sitter-save-excursion`. It keeps the cursor on the same node, and on the same vertical position.

The following works for me in Python (provided that `tree-sitter-mode` is turned on in the buffer), with Black formatter:

```emacs-lisp
(require 'tree-sitter-extras)

(define-advice format-all-buffer (:around (f &rest args) tree-sitter-save-excursion)
  (if tree-sitter-mode
      (tree-sitter-save-excursion
        (apply f args))
    (apply f args)))
```

I think it's better to combine this with the diff-based approach mentioned in the issue you linked, though.

**Comment by leungbk** [comment]
@raxod502, who wrote `apheleia.el`, is knowledgeable about this. If we use Needleman-Wunsch as with `apheleia`, it's not clear to me how we'd combine this with a `tree-sitter`-based approach.

**Comment by raxod502** [comment]
Yes, there are basically two good options for handling this issue:
* The smart approach, which is to have an understanding of the AST and the cursor's position within a specific node
* The dumb approach, which is to use a string alignment or regexp-based algorithm

If you've got the resources available to do the first approach, it'll probably work better. The reason I think the second approach is good is because the first approach requires a lot of work for each language / formatter, whereas the second approach works for all languages and formatters.

The disadvantages of the second approach are:
* it needs some heuristics to optimize for large diff regions, because the dynamic programming algorithm scales quadratically (https://github.com/raxod502/apheleia/issues/4)
* it needs some heuristics to nudge the cursor to the most appropriate position sometimes, because the dynamic programming algorithm can select one of several different string alignments which score equally well but which do not seem equally appropriate to a user (https://github.com/raxod502/apheleia/issues/2)
